### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by viddie** [yoshiyoshyosh/goldberries#62]
Everything that has to be done for the final migration:
- [x] Disable account modification in backend (registration, account update/delete), disable submissions
- [x] Save account data (just as backup)
- [x] Reset all player claims
- [x] Save account data again (this will be the actually migrated data)
- [x] Re-run DB build script
- [x] Apply default data
- [x] Apply migrated data
- [x] Run `UPDATE submission SET is_verified = true`
- [x] Run `UPDATE submission SET date_created = NULL`
- [x] Run campaign fixer for SJ and Winter Collab (& run campaign structure import)
- [x] Check new youtube & bilibili links
  - [x] Download new links
  - [x] Run processing script to fetch new links
  - [x] Put returned data on server
  - [x] Run script to import parsed data into goldberries database
- [x] Update frontend:
  - [x] Navigation: SJ, Winter Collab, D-Sides, Lunar Ruins -> Spring Collab
  - [x] Index: Public Test Notice -> Newly Released
  - [x] Cost Overview: Shrimp Contest ID
  - [x] Submit: Remove pre-release notice
  - [x] Top Golden List: Remove pre-release notice
- [x] Update backend:
  - [x] Disable challenge change webhooks
  - [x] Re-enable account modification and submissions
